### ISSUE TITLE
Rename repository from `charts` to a meaningful name

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/kubernetes-management#1649]
Since #1642 where the charts are moved out to `public-charts`, then the current name `charts` has lost its meaning.
We should find a new name that capture the fact that this repository hosts the "applications" we are installing on our k8s clusters.

**Comment by timja** [comment]
I would probably rename public-charts to charts, public-charts doesn't make sense to me

**Comment by timja** [comment]
kubernetes maybe? kubernetes-definitions

**Comment by lemeurherve** [comment]
"kubernetes-infra-setup"?
"kubernetes-infra-config"?
"kubernetes-infra-state"?

Maybe with "k8s" like "k8s-infra-setup"?

**Comment by dduportal** [comment]
Done in december 2021
