### ISSUE TITLE
Manage datadog app's docker image tag

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/kubernetes-management#1707]
To be implemented:

- [ ] Update the datadog app's helmfile values to specify the tag image (and pull policy to ifnotpresent)
- [ ] Add an updatecli manifest to track the docker image tag

**Comment by lemeurherve** [comment]
Closed with #1709

**Comment by lemeurherve** [comment]
https://github.com/jenkins-infra/charts/blob/f35f0b83b57a64bb0e8bc427a713617e81cd9659/updatecli/updatecli.d/docker-images/datadog.yaml#L16

**Comment by dduportal** [comment]
Not needed since https://github.com/jenkins-infra/kubernetes-management/pull/3919
