### ISSUE TITLE
Delete the ec2 `amiType` blocs as `22` is already the default `sshPort` value

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/kubernetes-management#2722]
"22" is already the default sshPort value, we can delete each of these blocs.

https://github.com/jenkins-infra/kubernetes-management/blob/fd35d990833d90d215bd7184e27510748b85b98a/config/ext_jenkins-infra.yaml#L223-L225

_Originally posted by @lemeurherve in https://github.com/jenkins-infra/kubernetes-management/pull/2721#discussion_r949556685_

**Comment by dduportal** [comment]
The goal was to make it explicit that:
- SSH is used 
- Even on windows
- The default 22 port is used 


Maybe worth a comment as i wasn’t able to make it work reliably back in time : try it without the block and let’s see
