### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/kubernetes-management#2924]
- (Re)move the [How to Contribute to an Existing Chart](https://github.com/jenkins-infra/kubernetes-management/blob/main/CONTRIBUTING.md#how-to-contribute-to-an-existing-chart) section as our helm charts aren't included in this repository anymore. They are now here: https://github.com/jenkins-infra/helm-charts

- Add a section how to debug deployments, with (for example) `helmfile template  --no-color -f clusters/<cluster-name>.yaml -l name=<release-name>`

**Comment by ADITYADAS1999** [comment]
hi [lemeurherve](https://github.com/lemeurherve) this issue is still open to work ? Can I work with this by make a PR?

**Comment by dduportal** [comment]
Hi @ADITYADAS1999 yes you can this issue.

**Comment by ADITYADAS1999** [comment]
hey [dduportal](https://github.com/dduportal) can you review the PR,  https://github.com/jenkins-infra/kubernetes-management/pull/3339

**Comment by lemeurherve** [comment]
Completed by @ADITYADAS1999 in #3339, thanks!
