### ISSUE TITLE
Plugin to Configuring Kubernetes Credentials On Jenkins Server

### ISSUE THREAD

**Issue by sitaorg2022** [jenkins-infra/kubernetes-management#3529]
Any recommendation for the jenkins plugin to configure   Kubernetes Credentials 
"https://plugins.jenkins.io/kubernetes-cd/"  is suspended.

**Comment by dduportal** [comment]
Hi @sitaorg2022 , this issue tracker is only scoped to the Jenins public infrastructure.

If you need help, you will get better exposure by opening a discussion topic to ask your question in the community.jenkins.io forums.

I'm closing this issue as it is unrelated to the Jenkins infrastructure.


PS: you might be interested in https://plugins.jenkins.io/kubernetes-credentials/ :)
