### ISSUE TITLE
Don't set mirrorbits `httpd` Docker image tag as it's already kept up to date in mirrorbits chart

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/kubernetes-management#4212]
~https://github.com/jenkins-infra/kubernetes-management/blob/21b7e73659700b7afaf1ffda08fb6b19b93cab2f/config/mirrorbits.yaml#L7-L8~

See https://github.com/jenkins-infra/kubernetes-management/issues/4212#issuecomment-1668245966

**Comment by karthikmurali60** [comment]
Hi @lemeurherve !!

Can i work on this issue ?

**Comment by lemeurherve** [comment]
@karthikmurali60 sure 🙂

**Comment by lemeurherve** [comment]
> Looking at [[jenkins-infra/helm-charts/blob/main/updatecli/updatecli.d/mirrorbits.yaml#L24-L32](https://github.com/jenkins-infra/helm-charts/blob/main/updatecli/updatecli.d/mirrorbits.yaml#L24-L32)], I realize the issue #4212 isn't needed, but instead the `httpd` tag should be removed from mirrorbits values at https://github.com/jenkins-infra/kubernetes-management/blob/d65ba387616155b588505174dd6a6a42f0a58986/config/mirrorbits.yaml#L8-L9 as this tag is already kept up to date in the mirrorbits helm chart.

_Originally posted by @lemeurherve in https://github.com/jenkins-infra/kubernetes-management/issues/4214#issuecomment-1668242864_
